version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techstart-fashion
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
