version: "3"
services:
  fashion-node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - mysql
      - redis
    command: npm run start
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  redis:
    image: redis
