version: "3"

services:
  gateway:
    container_name: api-gateway
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - product
      - feed
      - scanner
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  product:
    container_name: product-service
    build: ./product-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/product
    depends_on:
      - mysql
    networks:
      - backend

  feed:
    container_name: feed-service
    build: ./feed-service
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - backend

  scanner:
    container_name: scanner-service
    build: ./scanner-service
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql:

networks:
  backend:
    driver: bridge
