export enum Synthetic {
  NYLON = "NYLON",
  POLYESTER = "POLYESTER",
  SPANDEX = "SPANDEX",
  ACETATE = "ACETATE",
  CUPRO = "CUPRO",
  FLANNEL = "FLANNEL",
  LYOCELL = "LYOCELL",
  PVC = "PVC",
  RAYON = "RAYON",
  PET = "PET",
  TYVEK = "TYVEK",
  VINYLON = "VINYLON",
}
