name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
      
jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: cd backend && npm install

      - name: Test
        run: cd backend && npm run test
