name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd backend && npm install

      - name: Build
        run: cd backend && npm run build
