name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
      
jobs:

  testing:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:root@localhost:3306/techstart-fashion
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: cd backend && npm install

      - name: Start volume
        run: docker volume create db

      - name: Start database
        run: docker run -d \
              --name db \
              -e MYSQL_ROOT_PASSWORD=root \
              -e MYSQL_DATABASE=techstart-fashion \
              -p 3306:3306 \
              -v db:/var/lib/mysql \
              --restart always \
              mysql

      - name: Test
        run: cd backend && npm run test
